### ISSUE TITLE
Prepare deploy

### ISSUE THREAD

**Issue by vojtasvoboda** [BarcampPraha/prazskybarcamp.cz#22]
Automatic deployment from GitHub to Heroku or PagodaBox?

Give a try https://github.com/integrations/runnable

**Comment by tomaskazatel** [comment]
@vojtasvoboda jak dopadlo toto? Máme už to kde ukazovat?

**Comment by vojtasvoboda** [comment]
@tomaskazatel Budu řešit dnes. Zatím to jede pořád na http://prazskybarcamp-cz.gopagoda.io/ ale není to sestavené úplně ideálně :-(
