### ISSUE TITLE
Grafické upravy

### ISSUE THREAD

**Issue by ZdenekCulik** [BarcampPraha/prazskybarcamp.cz#56]
písmo gilroy neukazuje diakritiku, například u žádání newsletteru.
<img width="515" alt="snimek obrazovky 2017-02-11 v 18 20 14" src="https://cloud.githubusercontent.com/assets/25708769/22855836/c54aff22-f086-11e6-84e5-629409cebf92.png">

hlavní page
At to začíná videem jak být profi v tom co tě baví a at to tam je kldině o 2s déle
1) **Jak být profi** at stojí na místě, at neskáče zleva doprava. A text vedle at se mení box efektem jak jsem psal v popisku webu.
2) subheadline ,,Přijď si poslechnout profesionály...., zmensit řádkování. 
3) vymenit ikony (ulozim a poslu) https://drive.google.com/open?id=0B-DZnAuZWAMAeDhJWG1JdFJycmc
4) 10důvodů proč nad tím neohrnout nos a text pod tím. Změnit řádkování. Text má mít menší řádkování, naopak odsazení za řádkem je oka. 
5) U jmen přednášejících zkusit zvětšit rozpal písma at je to lépe čitelné
6) texty v buttonech nejsou an středu, jsou mírně nad středem.
7) opravit popup (zasekaný ,,bounce,,)
8) fotky v profilovkách jsou deformované a hrozně low quality, jakto?
9) ŠEDÝ BACKROUND je pouze pod newsletterem (ted je i pod blogem)
10) u registrace má být 2buttony, messenger a eventbrite
11) patička nefugue hlasovat pro přednášejícího (scroll na část hlasování)
12) na mobilu (android, poslední verze chromu) se nanačítá hlaví slide
13) hrozně dlouho to trvá a začne se neco načítat když kliknu na ,,hlasovat,, prosím zrychlit at je to na click.
14) pod buttonem u partneru ma byt chci být partner

Jinak skvělá práce! klobouk dolů!

**Comment by tomaskazatel** [comment]
- [ ] písmo gilroy neukazuje diakritiku, například u žádání newsletteru
- [ ] at to začíná videem jak být profi v tom co tě baví a at to tam je kldině o 2s déle
- [ ] jak být profi at stojí na místě, at neskáče zleva doprava. A text vedle at se mení box efektem jak jsem psal v popisku webu.
- [ ] subheadline ,,Přijď si poslechnout profesionály...., zmensit řádkování.
- [ ] vymenit ikony (ulozim a poslu)
- [ ] 10důvodů proč nad tím neohrnout nos a text pod tím. Změnit řádkování. Text má mít menší řádkování, naopak odsazení za řádkem je oka.
- [ ] u jmen přednášejících zkusit zvětšit rozpal písma at je to lépe čitelné
- [ ] texty v buttonech nejsou an středu, jsou mírně nad středem.
- [ ] opravit popup (zasekaný ,,bounce,,)
- [ ] fotky v profilovkách jsou deformované a hrozně low quality, jakto?
- [ ] ŠEDÝ BACKROUND je pouze pod newsletterem (ted je i pod blogem)
- [ ] u registrace má být 2buttony, messenger a eventbrite
- [ ] patička nefugue hlasovat pro přednášejícího (scroll na část hlasování)
- [ ] na mobilu (android, poslední verze chromu) se nanačítá hlaví slide
- [ ] hrozně dlouho to trvá a začne se neco načítat když kliknu na ,,hlasovat,, prosím zrychlit at je to na click.

**Comment by tomaskazatel** [comment]
Closed by #57
