### ISSUE TITLE
Report - chyby

### ISSUE THREAD

**Issue by zdendablazek** [BarcampPraha/prazskybarcamp.cz#58]
Ahoj pánové, 

musím pochválit, web se povedl! 
Za mě si dovolím uvést ještě pár nedostatků, které je potřeba doladit:

AD. HOME
1. Pokud nechám chvilku déle načtenou hlavní stranu (cca 3 minuty - na Chrome), tak začne špatná synchronizace podkresového videa s hlavní zprávou (viz. obrázek)
![homepage___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862196/961351b0-f12a-11e6-87f8-91c65df8170b.png)
Ideální pokud by "Jak být profi" zůstávalo pořád na stejném místě.

2. Uspořádání bych dal takto:
V tom co tě baví > Gamer > Speaker > Kreslíř > Architekt

3. Text pod hlavní výzvou bych dal větší.
![homepage___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862214/f0da49a0-f12a-11e6-9754-bde67bb8c9c5.png)

AD. O BARCAMPU
4. Pozor na zarovnání textu:
![homepage___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862233/48681440-f12b-11e6-9af5-714e5ab73b46.png)

**Osobně bych asi raději, aby byl jeden odstavec, kde 10 důvodů by následovalo až po odstavci "Přivoň si k profi kariéře. Tím by se i všechny body v desateru vešly na jeden řádek. A vypadalo by to lépe. 
Takto je v levém sloupci zbytečně moc volného prostoru....pokud nevyplníme grafikou třeba Heřmana, který prchá před dronem..:)** 

AD. PŘEDNÁŠEJÍCÍ
...bude možné uvádět "Nejvíce hlasů" a "Nejnovější" dle grafické návrhu?

5. Nebude povolena funkce "filtrace" (po kliknutí na jednu z variant)?
![cursor_and_homepage___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862283/0cde0cd0-f12c-11e6-8043-915b01a28148.png)

6. Po kliknutí na jméno musí být pop-up rychlejší (=hned). Nyní zpoždění 1-2sec!!! Záleží jak je karta plná obsahem. Musí být odezva všude stejně.

7. Jména přednášejících bych ještě zvětšil.

8. Dá se upravovat v backendu? Zde chybně ikonka Twitteru > má být Instagram:
![cursor_and_homepage___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862298/49adc1be-f12c-11e6-8ac5-5d8ed19294c4.png)

9. Jaký je správný formát pro fotku - profilovka. Některé se budou muset "upravit.

AD. CHCI PŘEDNÁŠET
10. Upravit nápis:
![registrace___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862418/606a8688-f12e-11e6-8f19-761c480deac2.png)
To samé ve variantě - workshop

11. Uvést doporučený formát a velikost fotky
![registrace___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862434/d424309c-f12e-11e6-9b65-7a9bf2527a7f.png)

12. V případě "workshopu"
![registrace___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862451/231d7ba4-f12f-11e6-978e-56fc82e8378d.png)

AD. INSTAGRAM BOX
- zcela chybí "lidé co chtějí #být profi

AD. NEWSLETTER (může/nemusí)
Každopádně chybí "dvojtečka", dle návrhu COPY
![homepage___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862725/67eca0e8-f134-11e6-8f74-a71a6bd06f21.png)

AD. FAQ
13. Za mě velmi drobným písmem. Prohodit pořadí "Zaparkuji na místě a Jak se tam dostanu"
![homepage___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862738/abc8ac1c-f134-11e6-9f01-a4a626b0eb32.png)

AD. PARTNEŘI
14. Prosím upravit, máme tyto kategorie partnerů (mediální partneři až na konec)
Generální partner (1 pozice)
Zlatí partneři (2 pozice)
Stříbrní partneři (3 pozice)
Bronzoví partneři (5 pozic)
Partneři (10 pozic)
Mediální partneři
![homepage___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/22862553/40294668-f131-11e6-8c0f-1afe452b0ec0.png)
....viz. https://www.eshopsummit.cz/#partners 

AD. PROGRAM
Alespoň přidat informaci - 
Jste tu brzo. Program bude zveřejněn od 25. 3. a je závislý na výsledcích hlasování. 

AD. KONTAKT
Lidé v týmu, kteří stojí za Barcampem - proklik z fotky na LinkedIn nebo Facebook. Navíc umožnit proklik přes odkaz ve jménu - ten povede na případný osobní web osoby.

Moc se mi nelíbí ve struktuře "Materiály ke stažení" v sekci Kontakty. 

AD. PATIČKA
(+)Struktura patičky - OK
(-)Odkazy nefungují
(-)Chybí odkazy na sociální sítě přes ikony (viz. grafický návrh)

CHYBÍ:
Registrace na konferenci přes:
1) Eventbrite
2) Messenger (bot)

Díky Tomáši, Vojto, Zdeňku.

Zdenda

**Comment by tomaskazatel** [comment]
Closed by summary issue #59
