### ISSUE TITLE
Meta description - opravit

### ISSUE THREAD

**Issue by zdendablazek** [BarcampPraha/prazskybarcamp.cz#60]
zeptejsefilipa [8:19 PM] 

Meta description chybí:
http://takdem.eu/
http://takdem.eu/registrace
http://takdem.eu/program
http://takdem.eu/blog
http://takdem.eu/blog/dnesni-meeting-1222017
http://takdem.eu/kontakt

Meta Title tag doporučuji změnit na:
http://takdem.eu/ Konference o tom, jak být profi | Pražský Barcamp

Sekci Kontakt doporučuji změnit na Kontakty takto:
http://takdem.eu/kontakty Kontakty | Pražský Barcamp

Na hlavní straně se objevují 2x H1 nadpisy. 
Prosím vytvořte 1x a druhý dejte do H2.

Příliš velké obrázky:
http://takdem.eu/themes/barcamp/assets/images/1.png
http://takdem.eu/storage/app/media/meeting-rooms-for-traveling-professionals.jpg
http://takdem.eu/storage/app/uploads/public/58a/09a/eae/thumb_50_100x100_0_0_exact.png
http://takdem.eu/storage/app/uploads/public/58a/09b/190/thumb_51_100x100_0_0_exact.png
http://takdem.eu/storage/app/uploads/public/589/f18/467/thumb_28_100x100_0_0_exact.png

Doporučuji pro kompresi použít tento tool: https://compressor.io/

V mobilní verzi (landscape) se překrývají nadpisy: 
http://www.mobiopti.cz/vysledek/takdem.eu/

**Comment by vojtasvoboda** [comment]
Meta tagy doplněny; kontaktní stránka přejmenována - nutno udělat review a přesunout na hosting.

**Comment by tomaskazatel** [comment]
@vojtasvoboda super, zavírám issue a na hosting přidám s větším balíkem věcí. Díky
