### ISSUE TITLE
Copywriting feedback

### ISSUE THREAD

**Issue by ZdenekCulik** [BarcampPraha/prazskybarcamp.cz#66]
Úvodní header

- [x] U sousloví “V tom co tě baví” prosím o doplnění čárky: “v tom, co tě baví”
Přimlouval bych se za to, aby anvazující hesla typu “architekt”, “gamer” apod. byly malými písmeny. Tak to dle mého názoru bude lépe navazovat na "jak být profi" (asi nejvíce mi to vadí při sousloví “v tom, co tě baví”, kde to vinou velkého písmena “V” nepůsobí jako jedno sdělení).

- [x] Úvodní desatero
V bodě 6 prosím o doplnění čárky za prvním slovem: “Hned, co”. To je nejspíš moje chyba, omlouvám se.

- [ ]  chybý diakritika u **Ať**
<img width="509" alt="snimek obrazovky 2017-02-14 v 21 47 29" src="https://cloud.githubusercontent.com/assets/25708769/22948569/4b351760-f2ff-11e6-8a02-1a6c83ed1780.png">

**Comment by tomaskazatel** [comment]
@ZdenekCulik: všechno je fix, kromě toho "ť" tam je prozměnu problém s fontem 😄 

![snimek obrazovky 2017-02-15 v 13 48 47](https://cloud.githubusercontent.com/assets/5907185/22975141/d584c286-f385-11e6-9dae-638d43da3ac8.png)

Takže tohle issue zavírám a musíme případně pořešit font. Ve finále je to jen jedno písmenko na celém webu, tak nevím jestli s ek vůli tomu s tím srát.
