### ISSUE TITLE
úpravy na webu

### ISSUE THREAD

**Issue by ZdenekCulik** [BarcampPraha/prazskybarcamp.cz#72]
- [x] FAQ, otevřené pole mají mít **,,mínus,,**
- [x] Upavit copy: Ať ti nevyfouknou místo! Registruj se hned teď **jednou z možností.** Zbývá už jen 220 míst.
- [x] přidat heřmana
- [x] Burger na menu ať vypadá jako v návrhu tady (a odkaz na messenger je tady špatně, nevede na heřmana – na hlavní straně je správný odkaz)
- [x] lépe zarovnat text a upravit buttony at jsou stejně velké jako všechny ostatní na webu viz návrh.
- [x] FAQ při rozkliku tam ma byt ,,**minus**,, a otazky i text zarovnany na levy prapor a at nezačínají u toho +. stejně tak upravit na desktopu
- [x] upravit sazbu a copy textu
- [x] rozkliknutý článek - posunout headline na střed, takto zasahuje skoro do loga.
- [x]  Na nobilu řazení pod sebe je vpořádku ale na desktopu nechat jméno na jednom řádku.
- [x]  upravit nápovědu na +420 123 456 789 (+420 a mezery)
- [x] REGISTRACE - pokud cokoliv nevyplním nebo špatně vyplním tak mi to hodí hlášku, což je vpořádku. Ale vždycky s tím vypadne i zaškrtnuté pole jestli PRAXE nebo VZDĚLÁVÁNÍ a vymaže se fotka. prosím fix it at to tam zůstává.
- [x] registrace - fotka
- [x] patička
- [x] odstranit testovací položky
- [x] přidavnání nových článkun a blog nefunguje, pls fix.
- [x] bug - poslala jsem odkaz na blog kamaradovi a jemu se v textu tecky zobrazovali jak carky, muze to byt prohlizecem? Safari na iphonu
- [x] odstavcové styly v blogu taky na levý prapor
- [x] upravit text

No Fix for that 
- několik lidí z organizátorů jsou zárověn přednášející
- tento článek nemá svoji url

**Comment by tomaskazatel** [comment]
Closed by #79
