### ISSUE TITLE
Při registraci

### ISSUE THREAD

**Issue by zdendablazek** [BarcampPraha/prazskybarcamp.cz#73]
Ahoj, 

Zkoušel jsem se zaregistrovat na WORKSHOP. 

V momentě kdy jsem dal odeslat formulář -> šup nové načtení ....potvrzení sice jo - pouze jednou větou. 
A na první pohled mám jako registrovaný (chtěl jsem workshop) pocit, že jsem se registroval jako Speaker? Trošku zmatek.

![registrace___prazsky_barcamp](https://cloud.githubusercontent.com/assets/25721798/23106304/8a623c20-f6eb-11e6-90a1-dffe947c2466.png)

Zároveň bych větu doplnil:

**Vaše registrace byla úspěšně dokončena. Počkejte až se Vám ozve naše programová vedoucí.**

Díky

**Comment by tomaskazatel** [comment]
@vojtasvoboda povede se ti dneska vyřešit tohle?

**Comment by tomaskazatel** [comment]
S tím souvisí toto @vojtasvoboda :

- [ ]  prosím upravit text na 
**Vaše registrace byla úspešně dokončena. Brzy se vám ozveme.** 

<img width="1071" alt="snimek obrazovky 2017-02-18 v 16 08 13" src="https://cloud.githubusercontent.com/assets/25708769/23094181/80503680-f5f4-11e6-9a40-b47bfaaa608e.png">

**Comment by vojtasvoboda** [comment]
Ahoj, pořešeno v rámci #80 nyní to vypadá po registraci workshopu takto:

![snimek obrazovky 2017-02-22 v 20 08 57](https://cloud.githubusercontent.com/assets/374917/23228289/464adaee-f93c-11e6-9fbc-8e36abc51063.png)
