### ISSUE TITLE
GTM + GA

### ISSUE THREAD

**Issue by zdendablazek** [BarcampPraha/prazskybarcamp.cz#75]
Kod pro Google Tag Manager

<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-5J7SNH"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5J7SNH');</script>

Kód pro GOOGLE ANALYTICS

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-83609115-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by vojtasvoboda** [comment]
Stačí nám tedy pouze kód pro GTM, zbytek bude nasazeno pomocí GTM, takže kód pro GA není potřeba.

**Comment by zdendablazek** [comment]
OK, může být. Díky

**Comment by vojtasvoboda** [comment]
GTM kód nasazen, na produkčním webu se tedy objeví a bude tedy potřeba pak nakonfigurovat GTM a dát do něho GA+Facebook Pixel.

**Comment by zdendablazek** [comment]
OK, díky Vojto.
