### ISSUE TITLE
Pročistit branche pls

### ISSUE THREAD

**Issue by tomaskazatel** [BarcampPraha/prazskybarcamp.cz#82]
Kouni do branchů a zavři ty, které už nejsou potřeba prosím.

**Comment by vojtasvoboda** [comment]
Promazáno, ty dvě co tam jsou zatím ještě používám na testing nějakých doladění.

**Comment by vojtasvoboda** [comment]
Tj ty moje jsou feature/coveralls a feature/reg-form. Zbytek budou asi branche na kódování.
