### ISSUE TITLE
Tomáš

### ISSUE THREAD

**Issue by ZdenekCulik** [BarcampPraha/prazskybarcamp.cz#88]
- [x] v sekci přednášející se roztahují fotky po kliku na přednášejícího v jeho kartě.
<img width="351" alt="snimek obrazovky 2017-03-04 v 18 05 49" src="https://cloud.githubusercontent.com/assets/25708769/23580614/52c57e5c-0105-11e7-9e38-2590ca0c231b.png">
<img width="357" alt="snimek obrazovky 2017-03-04 v 18 05 54" src="https://cloud.githubusercontent.com/assets/25708769/23580615/52c76302-0105-11e7-9e8a-9a4c6b4dbbbd.png">

**Comment by tomaskazatel** [comment]
This is done.
